name: build-tiga-case

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: deploy_image/tiga-case
  REPOSITORY: 'lowcode-yunti/tiga-case'
  BRANCH_NAME: main
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY_SHANGHAI }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Get the latest commit SHA of the repository
        id: get-sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Get current date
        id: current-date
        run: echo "::set-output name=date::$(TZ=Asia/Shanghai date +'%Y-%m-%d-%H-%M-%S')"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}-backend:${{ env.BRANCH_NAME }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}-backend:${{ env.BRANCH_NAME }}-${{ steps.current-date.outputs.date }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}-backend:${{ steps.get-sha.outputs.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}-frontend:${{ env.BRANCH_NAME }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}-frontend:${{ env.BRANCH_NAME }}-${{ steps.current-date.outputs.date }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}-frontend:${{ steps.get-sha.outputs.sha }}
          labels: ${{ steps.meta.outputs.labels }}